# permissions for end users to view httpclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpclient-viewer-role
rules:
- apiGroups:
  - myapp.cncamp.io.example.com
  resources:
  - httpclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myapp.cncamp.io.example.com
  resources:
  - httpclients/status
  verbs:
  - get
