# permissions for end users to view httpclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpclient-viewer-role
rules:
- apiGroups:
  - apps.cncamp.io
  resources:
  - httpclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.cncamp.io
  resources:
  - httpclients/status
  verbs:
  - get
