# permissions for end users to edit httpclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpclient-editor-role
rules:
- apiGroups:
  - apps.cncamp.io
  resources:
  - httpclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.cncamp.io
  resources:
  - httpclients/status
  verbs:
  - get
