
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - myapp.cncamp.io.example.com
  resources:
  - httpclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myapp.cncamp.io.example.com
  resources:
  - httpclients/finalizers
  verbs:
  - update
- apiGroups:
  - myapp.cncamp.io.example.com
  resources:
  - httpclients/status
  verbs:
  - get
  - patch
  - update
